print("*"*45)
albb = ("阿里巴巴员工管理系统")
print(albb.center(35))
print("*"*45)
name = input("请输入您的姓名")
age = input("请输入您的年龄")
number = input("请输入您的工号")
time = input("请输入您的入职日期")
gangwei = input("请输入您的岗位")
money = input("请输入您的月薪")
    print("姓名%s":name\t"年龄%s":age\t"工号%s":number\t"日期%s":time\t"岗位%s":gangwei\t"月薪%s":money)
