address = ['瑞士','澳大利亚','新西兰','巴黎','英国']
print(address)
print('-'*40)
print(sorted(address))
print(address)
print('-'*40)
address.sort(reverse=True)
print(address)
print('-'*40)
address.reverse()
print(address)
print('-'*40)
address.sort()
print(address)
print('-'*40)
address.sort(reverse=True)
print(address)
